// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/eternity-dash/BentoGrid.tsx": () => import("../components/mockups/eternity-dash/BentoGrid.tsx"),
  "./components/mockups/eternity-dash/Editorial.tsx": () => import("../components/mockups/eternity-dash/Editorial.tsx"),
  "./components/mockups/eternity-dash/FocusMode.tsx": () => import("../components/mockups/eternity-dash/FocusMode.tsx")
};
